export { default as Home } from "./Home";
export { default as About } from "./About";
export { default as Profile } from "./Profile";
export { default as Repo } from "./Repo";
export { default as NotFound } from "./NotFound";
export { default as ProfileView } from "./ProfileView";
export { default as Activity } from "./Activity";
export { default as Followers } from "./Followers";
export { default as Following } from "./Following";
